module.exports = {
  apps: [
    {
      name: 'server',
      script: './apps/server/server',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        PATH: `${process.env.HOME}/.bun/bin:${process.env.PATH}`,
      },
      log_file: './apps/server/logs/combined.log',
      out_file: './apps/server/logs/out.log',
      error_file: './apps/server/logs/error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '1G',
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      kill_timeout: 5000,
    },
    {
      name: 'web',
      script: './apps/web/.output/server/index.mjs',
      interpreter: 'bun',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        NUXT_PUBLIC_SERVER_URL: 'http://localhost:3000/api',
        PATH: `${process.env.HOME}/.bun/bin:${process.env.PATH}`,
      },
      log_file: './apps/web/logs/combined.log',
      out_file: './apps/web/logs/out.log',
      error_file: './apps/web/logs/error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '1G',
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      kill_timeout: 5000,
    },
  ],
};